services:
  postgres:
    image: postgres:16
    container_name: rust_server_postgres
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./core_api
    container_name: rust_server_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.production
    volumes:
      - ./core_api/service_account.json:/app/service_account.json:ro
    expose:
      - "7878"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  report_api:
    build: ./report_api
    container_name: rust_server_report_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.production
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: rust_server_nginx
    restart: always
    depends_on:
      - api
      - report_api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Comando modificado para recarregar as configurações a cada 6h (necessário para renovação do Certbot)
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: rust_server_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Acorda a cada 12 horas para checar se o certificado precisa ser renovado
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
