events {
    worker_connections 1024;
}

http {
    upstream rust_api {
        server api:7878;
    }

    upstream report_api {
        server report_api:3000;
    }

    # Bloco para receber a comunicação não-segura inicial e os desafios do Let's Encrypt
    server {
        listen 80;
        listen [::]:80;
        server_name remindcare.com.br;
        
        # Ponto de acesso que o Certbot usará para validar que você é o dono do domínio
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Força o redirecionamento de qualquer outra coisa (que não seja o desafio) para HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Bloco para comunicação segura criptografada (HTTPS)
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name remindcare.com.br;
        
        # Caminho dos certificados gerados pelo Certbot (o init-letsencrypt.sh colocará eles aqui)
        ssl_certificate /etc/letsencrypt/live/remindcare.com.br/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/remindcare.com.br/privkey.pem;
        
        # Configurações recomendadas de segurança SSL da Mozilla
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        # Repasse para a API em Rust
        location / {
            proxy_pass http://rust_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Repasse para a API de Relatórios em JavaScript (Node.js)
        location /api/v1/reports/ {
            proxy_pass http://report_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
